version: '2'
services:

  web:
    image: tomcat:7.0
    container_name: mytomcat
    ports:
     - "8082:8080"
    depends_on:
     - db
    hostname: mytomcat
    links:
     - db
    volumes:
     - ./tomcat/scripts/:/tmp/scripts
     - ./tomcat/conf:/usr/local/tomcat/conf
     - ./tomcat/webapps:/usr/local/tomcat/webapps
     - ./tomcat/logs:/usr/local/tomcat/logs
   
  db:
    image: mysql
    container_name: mysqldb
    ports:
     - "3306:3306"
    environment:
     - MYSQL_DATABASE=persondb
     - MYSQL_USER=test
     - MYSQL_PASSWORD=password
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
     - ./mysql/db:/var/lib/mysql
     - ./mysql/scripts:/tmp/scripts
 